language: node_js

node_js: "6"

os:
    - osx
    - linux

before_script:
    - ./scripts/travis-before-script.sh

script:
    - npm run dep
    - npm run build
    # - npm run lint
    - npm run unit-test
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run e2e-test; fi

after_failure:
    - ./scripts/travis-after-failure.sh

cache:
  directories:
    - node_modules

notifications:
    email:
        on_success: never
        on_failure: change

branches:
    only:
        - master

