language: node_js

node_js: "6"

os:
    - osx

before_script:
    - ./scripts/travis-before-script.sh

script:
    - npm run dep
    - npm run build
    - npm run test

after_failure:
    - ./scripts/travis-after-failure.sh

cache:
  directories:
    - node_modules

notifications:
    email:
        on_success: never
        on_failure: change




